require 'rake/clean'

file 'main.tex' => 'main.lagda.tex' do
  system "lhs2tex --agda main.lagda.tex -o main.tex"
end

file 'main.pdf' => [ 'main.tex' , 'preamble.tex' ] do
  system 'pdflatex main.tex'
  if $?.success?
    system 'bibtex main'
    system 'pdflatex main.tex'
    system 'pdflatex main.tex'
  end
end

task :build => 'main.pdf'

task :default => 'main.pdf' do
  system 'open main.pdf'
end

CLEAN.include('*.aux','*.bbl','*.blg','*.log','*.ptb')
CLOBBER.include('main.tex','main.pdf')
